[package]
name = "gcc-test"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[lib]
name = "gcc-test"
doctest = false

[build-dependencies]
gcc = { path = ".." }
