language: rust
rust:
  - 1.0.0
  - beta
  - nightly
sudo: false
install:
  - curl -sO https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - tar xf rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - rm -rf $HOME/rust/lib/rustlib/$TARGET
  - mv rust-$TRAVIS_RUST_VERSION-$TARGET/rustc/lib/rustlib/$TARGET $HOME/rust/lib/rustlib
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --manifest-path gcc-test/Cargo.toml --target $TARGET
  - cargo test --manifest-path gcc-test/Cargo.toml --target $TARGET --release
  - cargo doc
  - rustdoc --test README.md -L target/debug
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: ilbcq9zX+UaiBcwqkBGldeanbEQus9npLsi0/nF1PUxKbQsoWSVtVOehAD8Hy92D3hX2npIRyNL8GxBn85XEcBYc1h7DiWUhLcXfZie79v8Ly/qboHCfZLXlB1ofbypbyQfouEdOE9zHf0ZILYVpAgUkliv6KuVShsrKNlbn4QE=
  matrix:
    - TARGET=x86_64-unknown-linux-gnu
    - TARGET=i686-unknown-linux-gnu
notifications:
  email:
    on_success: never
os:
  - linux
addons:
  apt:
    packages:
      - g++-multilib
